application: oneapp
version: alpha-001
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /data
  static_dir: data
- url: /.*
  script: app.app
