application: oneapp-dev
version: alpha-002
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /data
  static_dir: data
- url: /icons
  static_dir: icons
- url: /.*
  script: app.app
